package com.solinia.solinia.Models;

public enum FactionStandingType {
	FACTION_ALLY, FACTION_WARMLY, FACTION_KINDLY, FACTION_AMIABLE, FACTION_INDIFFERENT, FACTION_APPREHENSIVE, FACTION_DUBIOUS, FACTION_THREATENLY, FACTION_SCOWLS

}
