package com.solinia.solinia.Models;

public enum HINT {
	NEED_TARGET, PICKEDUP_SPELL, HITTHEMBUTMISSED, HITYOUBUTMISSED, HITFORDMGBY, MASTERWUFULL, PETHITTHEMBUTMISSED, OOC_MESSAGE, DISCORD_MESSAGE, PET_BACKINGOFFTGT, PET_ATTACKINGTGT

}
