package com.solinia.solinia.Models;

public enum HINT {
	NEED_TARGET, PICKEDUP_SPELL, HITTHEMBUTMISSED, HITYOUBUTMISSED, HITFORDMGBY, MASTERWUFULL, PETHITTHEMBUTMISSED, OOC_MESSAGE, DISCORD_MESSAGE, PET_BACKINGOFFTGT, PET_ATTACKINGTGT, INSUFFICIENT_REAGENTS, RUNE_ABSORBED, SERVER_SAVE_BEGIN, SERVER_SAVE_FINISH, SPELL_INVALIDEFFECT, FOCUSEFFECTFLICKER, SPELL_WORN_OFF_OF, INSUFFICIENT_LEVEL_GEAR, FINISH_ABILITY, BEGIN_ABILITY, ITEM_DISCOVERED, ARTIFACT_DISCOVERED, CHARM_CHA_FAIL, EXCEEDED_CLAIMXP

}
