package com.solinia.solinia.Models;

public enum HINT {
	NEED_TARGET, PICKEDUP_SPELL, HITTHEMBUTMISSED, HITYOUBUTMISSED, HITFORDMGBY, MASTERWUFULL, PETHITTHEMBUTMISSED, OOC_MESSAGE, DISCORD_MESSAGE, PET_BACKINGOFFTGT, PET_ATTACKINGTGT, INSUFFICIENT_REAGENTS, RUNE_ABSORBED, SERVER_SAVE_BEGIN, SERVER_SAVE_FINISH, SPELL_INVALIDEFFECT, FOCUSEFFECTFLICKER, SPELL_WORN_OFF_OF, INSUFFICIENT_LEVEL_GEAR, FINISH_ABILITY, ITEM_DISCOVERED, ARTIFACT_DISCOVERED, CHARM_CHA_FAIL, EXCEEDED_CLAIMXP, CRITICAL_DMG, BER_CRITICAL_DMG, PLAYER_JOIN, STARTS_TO_SING, STOPS_SINGING, CAST_ON_YOU_SONG, CAST_ON_YOU,CAST_ON_OTHER_SONG, CAST_ON_OTHER, ASSASSINATES, SLAYUNDEAD, OTHER_BEGIN_ABILITY, INTERRUPTED, LOSTEXPERIENCE,GAINEXPERIENCE, BONUSEXPERIENCE, FACTION_GOTBETTER,FACTION_GOTWORSE,FACTION_COULDNOTGETBETTER,FACTION_COULDNOTGETWORSE, DUALWIELD,DOUBLEATTACK, NPC_BEGIN_ABILITY, PET_BEGIN_ABILITY

}
