package com.solinia.solinia.Utils;

import java.util.ArrayList;
import java.util.List;

public class UTF8Utils {
	public static final String HeartSymbol = "❤";
	public static List<String> GetRunic()
	{
		List<String> runic = new ArrayList<String>();
		runic.add("ᚠ");
		runic.add("ᚡ");
		runic.add("ᚢ");
		runic.add("ᚣ");
		runic.add("ᚤ");
		runic.add("ᚥ");
		runic.add("ᚦ");
		runic.add("ᚧ");
		runic.add("ᚨ");
		runic.add("ᚩ");
		runic.add("ᚪ");
		runic.add("ᚫ");
		runic.add("ᚬ");
		runic.add("ᚭ");
		runic.add("ᚮ");
		runic.add("ᚯ");
		runic.add("ᚰ");
		runic.add("ᚱ");
		runic.add("ᚲ");
		runic.add("ᚳ");
		runic.add("ᚴ");
		runic.add("ᚵ");
		runic.add("ᚶ");
		runic.add("ᚷ");
		runic.add("ᚸ");
		runic.add("ᚹ");
		runic.add("ᚺ");
		runic.add("ᚻ");
		runic.add("ᚼ");
		runic.add("ᚽ");
		runic.add("ᚾ");
		runic.add("ᚿ");
		runic.add("ᛀ");
		runic.add("ᛁ");
		runic.add("ᛂ");
		runic.add("ᛃ");
		runic.add("ᛄ");
		runic.add("ᛅ");
		runic.add("ᛆ");
		runic.add("ᛇ");
		runic.add("ᛈ");
		runic.add("ᛉ");
		runic.add("ᛊ");
		runic.add("ᛋ");
		runic.add("ᛌ");
		runic.add("ᛍ");
		runic.add("ᛎ");
		runic.add("ᛏ");
		runic.add("ᛐ");
		runic.add("ᛑ");
		runic.add("ᛒ");
		runic.add("ᛓ");
		runic.add("ᛔ");
		runic.add("ᛕ");
		runic.add("ᛖ");
		runic.add("ᛗ");
		runic.add("ᛘ");
		runic.add("ᛙ");
		runic.add("ᛚ");
		runic.add("ᛛ");
		runic.add("ᛜ");
		runic.add("ᛝ");
		runic.add("ᛞ");
		runic.add("ᛟ");
		runic.add("ᛠ");
		runic.add("ᛡ");
		runic.add("ᛢ");
		runic.add("ᛣ");
		runic.add("ᛤ");
		runic.add("ᛥ");
		runic.add("ᛦ");
		runic.add("ᛧ");
		runic.add("ᛨ");
		runic.add("ᛩ");
		runic.add("ᛪ");
		runic.add("᛫");
		runic.add("᛬");
		runic.add("᛭");
		runic.add("ᛮ");
		runic.add("ᛯ");
		runic.add("ᛰ");
		return runic;
	}
}
