name: Solinia3Core
main: com.solinia.solinia.Solinia3CorePlugin
version: 1.0
api-version: 1.13
commands:
  opencharcreation:
    description: Displays char creation
    usage: /opencharcreation
    aliases: []
  solinia:
    description: Displays additional information about Solinia3Core
    usage: /solinia
    aliases: []
  autoattack:
    description: Toggles your auto attack state
    usage: /autoattack
    aliases: []
  commit:
    description: Commits Solinia3Core State Data
    usage: /commit
    aliases: []
  sit:
    description: Toggles sit state
    usage: /sit
    aliases: []
  removevampirism:
    description: Removes vampirism from a player
    usage: /removevampirism mcname
    aliases: []
  openspellbook:
    description: Opens spellbook
    usage: /openspellbook
    aliases: []
  follow:
    description: Follows target
    usage: /follow
    aliases: []
  soliteminfo:
    description: Gets item info in main hand
    usage: /soliteminfo
    aliases: []
  consider:
    description: Considers the faction standing of your target
    usage: /consider
    aliases:
    - con   
  debugger:
    description: Debugs Solinia Core Functions
    usage: /debugger classname methodname focusid
    aliases: []
  transfercharacter:
    description: Transfers a character to another player
    usage: /transfercharacter <characteruuid> <playername>
    aliases: []
  memorisespell:
    description: Memorises a spell into spell slot
    usage: /memorisespell spellslotnumber spellid
    aliases:
    - memorise
  forename:
    description: Sets player forename
    usage: /forename <forename>
    aliases:
    - name
    - nick
  iamversion:
    description: Sets version
    usage: /iamversion <versionid>
    aliases:
    - castslot
  cast:
    description: Casts a spell from memory slot 1 to 0
    usage: /cast <memoryslot>
    aliases:
    - castslot
  givehead:
    description: Gives a head from minecraft-heads.com
    usage: /givehead player headurl
    aliases: []
  pray:
    description: Makes a prayer to the gods
    usage: /pray <prayer>
    aliases:
    - prayer
    - beseech
  today:
    description: Lists todays RP time
    usage: /today
    aliases: []
  flushdiscord:
    description: Empties discord queue
    usage: /flushdiscord
    aliases: []
  hidesongs:
    description: Hides songs
    usage: /hidesongs
    aliases: []
  stopsinging:
    description: Stops singing
    usage: /stopsinging
    aliases:
    - stopsong
  stopcasting:
    description: Stops casting a spell
    usage: /stopcasting
    aliases:
    - stopcast
  claimxp:
    description: Claims pending XP
    usage: /claimxp
    aliases: []
  bindwound:
    description: Binds your wounds with bandages
    usage: /bindwound
    aliases: 
    - bw
  lastname:
    description: Sets player lastname
    usage: /lastname <lastname>
    aliases: 
    - surname
  solignore:
    description: Ignores a player name in RPG chat (see /who for mcname)
    usage: /solignore <mcname>
    aliases: []
  mana:
    description: Gets player mana
    usage: /mana
    aliases: []
  showdiscord:
    description: Toggles showing of discord
    usage: /showdiscord
    aliases: []
  settitle:
    description: Sets a title
    usage: /settitle title
    aliases:
    - title
  quests:
    description: Lists quests
    usage: /quests
    aliases: []
  addrace:
    description: Creates a new race
    usage: /addrace racename strength stamina agility dexterity wisdom intelligence charisma adminonly
    aliases:
    - createrace
  setrace:
    description: Sets a players race
    usage: /setrace racename
    aliases:
    - race
  setgod:
    description: Sets a players god
    usage: /setgod godname
    aliases:
    - god
  creategod:
    description: Adds a new God
    usage: /addgod name
    aliases:
    - addgod
  addclass:
    description: Creates a new class
    usage: /addclass classname adminonly
    aliases:
    - createclass
  setclass:
    description: Sets a players class
    usage: /setclass classname
    aliases:
    - class
  addraceclass:
    description: Adds a class to a race
    usage: /addraceclass racename classname
    aliases: []
  stats:
    description: Gets player core stats
    usage: /stats
    aliases: []
  who:
    description: Lists online player details
    usage: /who
    aliases:
    - online
    - list
  editchunk:
    description: Edits a chunk
    usage: /editchunk
    aliases: []
  resetplayer:
    description: Resets players to a default state
    usage: /resetplayer <mcaccountname>
    aliases: []
  setgender:
    description: Sets players gender
    usage: /setgender male/female
    aliases:
    - gender
  emote:
    description: Emotes a message
    usage: /emote action
    aliases:
    - me
  bite:
    description: Bites your target
    usage: /bite mcplayername
    aliases:
    - me
  roll:
    description: Rolls a dice
    usage: /roll sides
    aliases:
    - random
    - dice
  setlanguage:
    description: Sets players language
    usage: /setlanguage language
    aliases:
    - language
  tarot:
    description: Deals a tarot card
    usage: /tarot
    aliases: []
  skills:
    description: Lists player skills
    usage: /skills
    aliases: []
  createitem:
    description: Creates item from the item you are holding
    usage: /createitem
    aliases: []
  listitems:
    description: Lists items
    usage: /listitems searchstring
    aliases: []
  listzones:
    description: Lists active zones
    usage: /listzones
    aliases: []
  listgods:
    description: Lists gods
    usage: /listgods
    aliases: []
  hotzones:
    description: Lists hot zones
    usage: /listhotzones
    aliases: []
  spawnitem:
    description: Spawns an item
    usage: /spawnitem itemid
    aliases: []
  spawnnpc:
    description: Spawns an npc
    usage: /spawnnpc npcid
    aliases: []
  spawnrandomitem:
    description: Spawns a random item
    usage: /spawnrandomitem
    aliases: []
  raceinfo:
    description: Lists race info
    usage: /raceinfo
    aliases: []
  godinfo:
    description: Lists god info
    usage: /godinfo
    aliases: []
  rebuildspellitems:
    description: Rebuilds spell items
    usage: /rebuildspellitems
    aliases: []
  createnpc:
    description: Creates a new npc
    usage: /createnpc factionid level npcname
    aliases:
    - addnpc
  createnpccopy:
    description: Creates a new npc from an existing npc
    usage: /createnpc ncpid npcname
    aliases:
    - addnpccopy
  createfaction:
    description: Creates a new faction
    usage: /createfaction basestandingvalue name
    aliases:
    - addfaction
  listfactions:
    description: Lists factions
    usage: /listfactions filter
    aliases: []
  listnpcs:
    description: Lists npcs
    usage: /listnpcs filter
    aliases: []
  editnpc:
    description: Edits an npc
    usage: /editnpc npcid setting value
    aliases: []
  npcsay:
    description: Makes npcs of this ID nearby say something
    usage: /npcsay npcid message
    aliases: []
  npcattack:
    description: Makes npcs of this ID add a nearby entity to a hate list
    usage: /npcattack npcid targetentityname
    aliases: []
  editspawngroup:
    description: Edits a spawngroup
    usage: /editspawngroup spawngroupid setting value
    aliases: []
  createloottable:
    description: Creates a new loot table
    usage: /createloottable name
    aliases: []
  createlootdrop:
    description: Creates a new loot drop table
    usage: /createlootdrop name
    aliases: []
  addlootdropitem:
    description: Adds an item to a loot drop
    usage: /addlootdropitem lootdropid itemid count always chance
    aliases: []
  addloottablelootdrop:
    description: Adds a loot drop table to a loot table
    usage: /addloottablelootdrop loottableid lootdropid
    aliases: []
  editspell:
    description: Edits a spell
    usage: /editspell spellid setting value
    aliases: []
  listloottables:
    description: Lists loottables
    usage: /listloottables filter
    aliases: []
  listlootdrops:
    description: Lists lootdrops
    usage: /listlootdrops filter
    aliases: []
  local:
    description: Speaks in local chat
    usage: /local message
    aliases:
    - say
    - l
  shout:
    description: Speaks in shout chat
    usage: /shout message
    aliases: []
  whisper:
    description: Speaks in whisper chat
    usage: /whisper message
    aliases: []
  forcelevel:
    description: Forces a players level
    usage: /forcelevel mcplayer level
    aliases: []
  scribeallspells:
    description: Scribes all spells up to level (if higher or equal)
    usage: /scribeallspells level
    aliases:
    - scribespells
  swearfealty:
    description: Swears fealty to a player
    usage: /swearfealty mcplayername
    aliases: []
  createalignment:
    description: Creates a new alignment
    usage: /createalignment name
    aliases: []
  createmerchantlist:
    description: Creates a merchant list
    usage: /createmerchantlist name
    aliases:
    - createmerchant
  editmerchantlist:
    description: Creates a merchant list
    usage: /editmerchantlist id setting value
    aliases:
    - editmerchant
  addmerchantitem:
    description: adds an item to a merchant list
    usage: /addmerchantitem merchantid itemid
    aliases: []
  npcgive:
    description: Gives an item to an npc you are interesting with
    usage: /npcgive itemid
    aliases: []
  listmerchantlists:
    description: Lists all merchant lists
    usage: /listmerchantlists
    aliases:
    - listmerchants
  edititem:
    description: Edits an item
    usage: /edititem itemid setting value
    aliases: []
  editclass:
    description: Edits a class
    usage: /editclass classid setting value
    aliases: []
  createspawngroup:
    description: Creates a new spawngroup
    usage: /createspawngroup npcid spawngroupname
    aliases: []
  listspawngroups:
    description: Lists spawngroups
    usage: /listspawngroups filter
    aliases: []
  updatespawngrouploc:
    description: Updates a spawngroups location
    usage: /updatespawngrouploc spawngroupid
    aliases: []
  setchannel:
    description: Sets current channel
    usage: /setchannel channelname
    aliases:
    - ch
    - channel
  ooc:
    description: Sends a message to the ooc channel
    usage: /ooc message
    aliases: []
  group:
    description: Group control commands
    usage: /group cmd
    aliases:
    - grp
    - grou
  groupchat:
    description: Sends a message to the group channel
    usage: /groupchat message
    aliases:
    - g
    - gc
  convertmerchanttolootdrop:
    description: Sends a message to the ooc channel
    usage: /convertmerchanttolootdrop merchantid
    aliases:
    - convertmerchant
  effects:
    description: Lists details regarding effects related to your character
    usage: /effects
    aliases: []
  createarmorset:
    description: Creates a new set of armour for a class
    usage: /createarmorset classid tier suffixname
    aliases: 
    - createarmourset
  createallarmoursets:
    description: Creates a new set of armour for all class with a chance of 10% on a lootdrop
    usage: /createallarmoursets lootdropid tier chance suffixname
    aliases: 
    - createallarmorsets
  listspells:
    description: Lists spells
    usage: /listspells searchstring
    aliases: []
  editlootdrop:
    description: Edits a loot drop
    usage: /editlootdrop lootdropid setting value
    aliases: []
  editloottable:
    description: Edits a loottable
    usage: /editloottable loottableid setting value
    aliases: []
  pet:
    description: Views pet information
    usage: /pet
    aliases: []
  trance:
    description: Falls into a meditative trance
    usage: /trance
    aliases:
    - settrance
    - tran
    - tr
  aa:
    description: Buy and list AAs
    usage: /aa
    aliases: []
  faction:
    description: Lists faction statuses
    usage: /fact
    aliases: []
  specialise:
    description: specialises in a specific skill
    usage: /specialise
    aliases:
    - specialize
  toggleaa:
    description: Toggles experience into AA gain
    usage: /toggleaa
    aliases: []
  createnpcevent:
    description: Creates an NPC event
    usage: /createnpcevent npcid eventtype trigger responsetype response
    aliases: cnpce
  editrace:
    description: Edits a race
    usage: /editrace raceid setting value
    aliases: []
  editgod:
    description: Edits a god
    usage: /editgod godid setting value
    aliases: []
  editalignment:
    description: Edits an alignment
    usage: /editalignment alignmentid setting value
    aliases: []
  editfaction:
    description: Edits a faction
    usage: /editfaction faction setting value
    aliases: []
  granttitle:
    description: Grants a title
    usage: /granttitle playername title
    aliases: []
  playeremote:
    description: Forces a player to emote a message
    usage: /playeremote minecraftname message
    aliases: []
  editnpcevent:
    description: Edits an npc event
    usage: /editnpcevent npcid triggername setting value
    aliases: []
  createquest:
    description: Creates a new quest
    usage: /createquest questcode
    aliases: []
  createzone:
    description: Creates a new zone
    usage: /createzone zonenamenospaces x y z
    aliases: []
  editzone:
    description: Edits a zone
    usage: /editzone zoneid setting value
    aliases: []
  zonetp:
    description: TPs to a zone
    usage: /zonetp zoneid
    aliases:
    - tpzone
  editaa:
    description: Edits an AA Ability
    usage: /editaa aaid setting value
    aliases: []
  claim:
    description: Claims an item
    usage: /claim <subcommand>
    aliases:
    - claims
  listaas:
    description: Lists aa abilities
    usage: /listaa searchstring
    aliases: []
  inspiration:
    description: Lists inspiration/buys inspiration rewards
    usage: /inspiration
    aliases:
    - vote
  loot:
    description: Searches loot
    usage: /loot searchstring
    aliases: []
  character:
    description: Character admin command
    usage: /character
    aliases: []
  hideooc:
    description: Toggles hiding of the OOC channel
    usage: /hideooc
    aliases:
    - toggleooc
  listnpcspells:
    description: Lists an npcs spell list
    usage: /listnpcspells
    aliases:
    - listnpcspelllists
    - listnpcspelllist
  listclasses:
    description: Lists classes
    usage: /listclasses
    aliases: []
  listraces:
    description: List races
    usage: /listraces
    aliases: []
  editnpcspelllist:
    description: Edits an npc spell list
    usage: /editnpcspelllist
    aliases:
    - editnpcspells
    - editnpcspell
    - editnpcspelllists
  skillcheck:
    description: Rolls a 1d20 for a skill check
    usage: /skillcheck <skill>
    aliases:
    - rollskill
  equip:
    description: Handles equipment configuration
    usage: /equip <options>
    aliases: []
  craft:
    description: Combines two items in your hands
    usage: /craft
    aliases: []
  createcraft:
    description: Creates a new crafting recipe
    usage: /createcraft recipenamenospaces itemid1 itemid2 outputitemid
    aliases: []
  editcraft:
    description: Edits a crafting recipe
    usage: /editcraft craftid setting value
    aliases: []
  listcrafts:
    description: Lists crafting recipes
    usage: /listcrafts
    aliases: []
  plantflag:
    description: Plant flag
    usage: /plantflag
    aliases:
    - placeflag
  trader:
    description: Trader menu
    usage: /trader
    aliases:
    - trade   
  editworld:
    description: Edits a world
    usage: /editworld worldid setting value
    aliases: []
  listworlds:
    description: Lists worlds
    usage: /listworlds
    aliases: []
  reagent:
    description: Reagent pouch control
    usage: /reagent <option>
    aliases:
    - reagents  
  setspouse:
    description: Sets your spouse
    usage: /setspouse mcname
    aliases:
    - spouse   
  setmother:
    description: Sets your mother
    usage: /setmother mcname
    aliases:
    - mother  
  setmain:
    description: Sets your current character as main
    usage: /setmother confirm
    aliases: []
  spellbook:
    description: Manipulates your spell book
    usage: /spellbook <arg> <arg>
    aliases:
    - spell
    - spells
  target:
    description: Selects a target
    usage: /target entityname OR /target nearestnpc OR /target self OR /target 2 etc for group member no 2 OR /target pet for target pet
    aliases:
    - gs
    - groupselect
    - tg
    - gt
    - grouptarget
    - targetgroup
    - targ
    - tgt
  listquests:
    description: Lists quests
    usage: /listquests searchstring
    aliases: []
  editquest:
    description: Edits a quest
    usage: /editquest questid setting value
    aliases: []
  publishbook:
    description: Publish book
    usage: /publishbook
    aliases: []
  oath:
    description: Select oath
    usage: /oath <select>
    aliases: []
  personality:
    description: View/set personality
    usage: /personality
    aliases: []
  resetpersonality:
    description: Resets players to a default personality state
    usage: /resetpersonality <mcaccountname>
    aliases: []
depend:
- Vault
- MythicMobs
- Votifier
- EffectLib
- Towny