name: Solinia Package

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
        
        
    - name: BuildTools
      run: |
        wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
        java -jar BuildTools.jar --rev 1.14.4 | grep -vE "[^/ ]*/[^/ ]*\s*KB\s*$" | grep -v "^\s*$":

    - name: Build with Maven
      run: |
        mvn -version
        export NOW=$(date +%s)
        echo $NOW
        cp .travis.settings.xml ~/.m2/settings.xml
        cp .travis.settings.xml /home/runner/work/solinia3-core/solinia3-core/settings.xml
        mvn -Drevision=1.14.4-R0.1-$NOW deploy

